### ISSUE TITLE
Extremely high memory usage

### ISSUE THREAD

**Issue by xvzf** [Red5/docker#6]
Hi there!

With just one stream and one client, I am facing memory consumptions of 45GB+ (on a Server with 144GB System Ram)

Has anybody faced this issue before?

**Comment by mondain** [comment]
Red5 doesnt use that much RAM especially at that load; my guess is that something else is going on or has run-away.

**Comment by xvzf** [comment]
Do you have any idea what the issue could be? It was the default docker container simply monitored with `docker stats` and it can be reproduced (not in such an extreme amount, but ~10GB memory utilization is seen everytime I tried it today).

**Comment by mondain** [comment]
I really have no idea; I've not heard of such a thing other than your report of this happening. Granted there isn't a lot of Docker use with Red5 to speak of, but at Red5 Pro we do have QA using it and Pro would generally be expected to have a much higher memory footprint than a standard Red5 server due to its expanded feature set.

**Comment by mondain** [comment]
We also use the Red5 1.0.10+ server as a base, so it might be the use of the older releases, a memory leak perhaps.

**Comment by xvzf** [comment]
I build the dockerimage myself and the issue resolved, maybe you should push an update to dockerhub.
